### ISSUE TITLE
Does the preprocessing step of the fairseq model have an impact on the original fairness of the dataset?

### ISSUE THREAD

**Issue by xyz321123** [zhjgao/difformer#1]
Thanks for this creative work.

And I wonder if the preprocessing steps of fairseq will change the fairness of the original dataset?
If so, can I use bert embeddings instead of the ones generated by fairseq preprocessing?

**Comment by zhjgao** [comment]
Hi, thanks for your interest in our work.

We apply the same preprocessing procedure for our experiments and reproductions, and of course, you can use your own dictionary in the preprocessing and training.
