### ISSUE TITLE
how do you obtain `transformer.pt`?

### ISSUE THREAD

**Issue by chenxwh** [zhjgao/difformer#2]
Thanks for making the code public!
In the evaluation script and the model released there is `transformer.pt`, assuming this is for reranking when b > 1? How do you obtain this model? I ran the training script but seems only the `difformer.pt` weights are saved?

**Comment by zhjgao** [comment]
Hi, Thanks for your interest in our work.

**Comment by zhjgao** [comment]
Hi, thanks for your interest in our work.

The `transformer.pt` here is an autoregressive model trained on the same dataset. You could train your own reranker following the instructions provided by Fairseq.
