### ISSUE TITLE
cannot reproduce results on `iwslt14_de_en`

### ISSUE THREAD

**Issue by chenxwh** [zhjgao/difformer#3]
Hi, I followed the instructions to prepare the datasets [here](https://github.com/facebookresearch/fairseq/tree/main/examples/translation#iwslt14-german-to-english-transformer), and then used the exact setting to train`iwslt14_de_en`, but I got the result for BLEU of 29.9 instead of 32.2 as reported in the paper.
`Generate test with beam=1: BLEU4 = 29.93, 64.0/37.2/23.1/14.6 (BP=1.000, ratio=1.011, syslen=132588, reflen=131156)`

Further more, if I use the ckpt I trained with the `transformer.pt` you shared for this dataset, it shows 
`size mismatch for encoder.embed_tokens.weight: copying a param with shape torch.Size([10096, 512]) from checkpoint, the shape in current model is torch.Size([10152, 512])` error, and I could not evaluate for b > 1 with my trained ckpt and the uploaded `transformer.pt` (however I should be able to since `transformer.pt` is trained separately on the same dataset).

Both make me wonder if the discrepancy comes from the differences in the training data. Can you please provide the _exact_ steps/script to prepare each of the datasets and also share the training/validate data-bin on Google drive?

Thank you!

**Comment by zhjgao** [comment]
Hi,
1. Did you perform knowledge distillation? The instructions can be found [here](https://github.com/facebookresearch/fairseq/tree/main/examples/nonautoregressive_translation#knowledge-distillation).
2. After distillation, make sure the distilled dataset shares the same vocabulary with `transformer.pt` in preprocessing. You could use the vocabulary we provide to preprocess the distilled dataset.

**Comment by vikyou** [comment]
Hello, author! 
1. I also encountered the first problem in the reproduction, which is "I got the result for BLEU of 29.9 instead of 32.2 as reported in the paper." For the iwslt14_de_en dataset, you mentioned in your paper "We use the distilled training set for WMT datasets and the original ones for other datasets." Does only the wmt data set need to be distilled?
2. Which document is "vocabulary" referring to？

**Comment by zhjgao** [comment]
> Hello, author!
> 
> 1. I also encountered the first problem in the reproduction, which is "I got the result for BLEU of 29.9 instead of 32.2 as reported in the paper." For the iwslt14_de_en dataset, you mentioned in your paper "We use the distilled training set for WMT datasets and the original ones for other datasets." Does only the wmt data set need to be distilled?
> 2. Which document is "vocabulary" referring to？

Hi,
1. Distillation is applied for all the machine translation datasets, including iwslt14_de_en.
2. The vocabulary refers to dictionary files, namely `dict.*.txt` files in the dataset folders.

**Comment by vikyou** [comment]
1. Is the transformer.py model you provide trained on undistilled data? Can I directly use the transformer.py you provided for distillation？
2. In addition, how can I use the vocabulary you provide to preprocess the distilled dataset?

**Comment by zhjgao** [comment]
> 1. Is the transformer.py model you provide trained on undistilled data? Can I directly use the transformer.py you provided for distillation？
> 2. In addition, how can I use the vocabulary you provide to preprocess the distilled dataset?

1. Our provided `transformer.pt` models are trained on the distilled datasets for fair comparisons, and the distillation should be adopted using Transformer trained on the raw datasets.
2. Here we would like to sort out the training and evaluation pipelines:
- If you would like to reimplement on the *raw* datasets:
    1. Train Difformer on the raw datasets.
    2. Train Transformer on the raw datasets to apply PPL-MBR, or directly apply BLEU-MBR (switch `--ppl-mbr` to `--bleu-mbr` and delete the path of the `transformer.pt` in the evaluation scriptes).
    3. Average the best 5 checkpoints using `scripts/average_checkpoints.py`.
    4. Evaluate the averaged checkpoint using `scripts/{DATASET}/evaluate.sh`.
- If you would like to reimplement on the *distilled* datasets as we reported:
    1. Train Transformer on the *raw* datasets as the teacher to adopt distillation.
    2. Train Difformer on the *distilled* datasets.
    3. Train Transformer and conduct evaluations on the *distilled* datasets.
