### ISSUE TITLE
Question regarding QQP / Wiki-Auto results

### ISSUE THREAD

**Issue by zzbuzzard** [zhjgao/difformer#6]
Hi! Thanks for open-sourcing this code.

In your README you list results of evaluating on QQP and Wiki-Auto, although these are not mentioned in the paper. What MBR size was used for these results? I assume "BLEU" in this table refers to the NLTK implementation?

Thanks.

**Comment by zhjgao** [comment]
Hi!
The total beam sizes are the same as used in translation tasks, and all BLEU scores are obtained by the built-in utilities in Fairseq. You may use your preferred tools for evaluation, but ensure uniformity in data preprocessing and post-processing procedures.
