### ISSUE TITLE
BLEU=26.08 on IWSLT14 DE->EN

### ISSUE THREAD

**Issue by chiral-carbon** [zhjgao/difformer#8]
Hi @zhjgao,

Thanks for publishing this interesting work! I trained the model according to the instructions and on the IWSLT14 DE->EN task got BLEU=26.08 which is 8 points below reported score. The last line of `output.txt`:
```
Generate test with beam=21: BLEU4 = 26.08, 65.3/36.5/21.8/13.2 (BP=0.906, ratio=0.911, syslen=119422, reflen=131156)
```
My training did stop though at the 512th epoch on its own, I made no changes to the hyperparams as mentioned in the README for this task and the training resources GPU were still available. Would longer resumed training help improve it to the reported score?

For checking this I downloaded the provided checkpoints for this task, and and Ioaded and ran them but there was a tensor size mismatch issue:
```
RuntimeError: Error(s) in loading state_dict for Difformer:
	size mismatch for encoder.embed_tokens.weight: copying a param with shape torch.Size([10096, 128]) from checkpoint, the shape in current model is torch.Size([10152, 128]).
	size mismatch for decoder.embed_tokens.weight: copying a param with shape torch.Size([10096, 128]) from checkpoint, the shape in current model is torch.Size([10152, 128]).
	size mismatch for decoder.output_projection.weight: copying a param with shape torch.Size([10096, 128]) from checkpoint, the shape in current model is torch.Size([10152, 128]).
```

When I trained the model, the files that were generated were named `checkpoint_best.pt`, `checkpoint_last.pt` and the last 10 `checkpoint_{epoch}.pt` files and 5 `checkpoint_best_bleu_{score}.pt` files. 
The checkpoints named `difformer.pt` and `transformer.pt` (as provided in the checkpoints folder and the original code for model path in `evaluate.sh` script) were not generated during replication so I wanted to understand what is the difference here and if this might be causing the provided checkpoints to not evaluate. 

Or were the tensor dimensions modified on training? I'm not sure how or why that would even happen but would appreciate any insights you might have.

Would appreciate a response, thanks!

**Comment by chiral-carbon** [comment]
Hi, I figured out that it might be because of the fairseq preprocessing dictionary size of iwslt14, even though I use the same fairseq version as mentioned in your README:
```
fairseq                   0.10.2                   pypi_0    pypi
```

The Python and PyTorch versions are also the same. 
```
Singularity> python --version
Python 3.8.18
Singularity> conda list| grep torch  
ffmpeg                    4.3                  hf484d3e_0    pytorch
pytorch                   1.11.0          py3.8_cuda11.3_cudnn8.2.0_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
torchaudio                0.11.0               py38_cu113    pytorch
torchvision               0.12.0               py38_cu113    pytorch
```

The dictionary size shows to be 10152 for me when I download and preprocess iwslt14 according to the instructions in your README from [here](https://github.com/facebookresearch/fairseq/tree/main/examples/translation). So I am not sure if the fairseq preprocessing for this dataset has changed since then or if you applied any custom preprocessing to reduce the size to 10096. 

Let me know if you did the latter or if you might have any idea as to why it happened, as I am unable to load and see the performance of your checkpoints compared to my training results. 

Thanks!

**Comment by zhjgao** [comment]
Hi, please refer to https://github.com/zhjgao/difformer/issues/3#issuecomment-2048956961
